services:
  db:
    container_name: sdms-DB
    image: postgres
    environment:
      POSTGRES_USER: pstojkov
      POSTGRES_PASSWORD: proba123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: