services:
  postgres_db:
    container_name: sdms-DB
    image: postgres
    environment:
      POSTGRES_USER: pstojkov
      POSTGRES_PASSWORD: proba123
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - backend_network
    restart: unless-stopped

  mongo_db:
    container_name: usdms-DB
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: pstojkov
      MONGO_INITDB_ROOT_PASSWORD: proba123
    networks:
      - backend_network
    volumes:
      - mongo_db:/data/db
      - /c/Users/petar/Downloads:/Downloads
    ports:
      - "27017:27017"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_db/keycloak
      KC_DB_USERNAME: pstojkov
      KC_DB_PASSWORD: proba123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KEYCLOAK_LOGLEVEL: DEBUG
      ROOT_LOGLEVEL: DEBUG
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    networks:
      - backend_network
    command:
      - start-dev
    restart: unless-stopped

networks:
  backend_network:
    driver: bridge

volumes:
  db:
  mongo_db: